### ISSUE TITLE
哪里出错了

### ISSUE THREAD

**Issue by benpo5** [Liuxianlu/pikpak_werbio#1]
![捕获](https://github.com/user-attachments/assets/5aa39bb6-9cb5-4ffb-a9e0-bb80f6ac4828)
Running on all addresses.
Use http://10.0.2.224:8081/ to access the application
当前日期:  2024-08-09 10:17:12.777369
无法匹配行: outlook.com
未能读取邮箱或密码

**Comment by Liuxianlu** [comment]
邮箱.txt文件中的格式应该是这样的，请检查是否正确， 微软邮箱账号----密码

**Comment by Liuxianlu** [comment]
如无法解决，请加我QQ 70340008
