### ISSUE TITLE
老板  https://user.mypikpak.com/credit/v1/report 接口 400

### ISSUE THREAD

**Issue by happy0717** [Liuxianlu/pikpak_werbio#4]
老板  想请问一下 https://user.mypikpak.com/credit/v1/report 这个接口是做什么用的呀，感觉得抓个包看看是不是官方改东西了 传入参数该接口回显 {'code': 400, 'error': 'invalid_argument', 'error_description': 'invalid status code: 400'}

请求内容：
https://user.mypikpak.com/credit/v1/report?deviceid=f34d40d0c7bb5a97efb78a2713b09885&captcha_token=ck0.XJ_lBGIpnkHMQkKtjUF8DskSGJD7wIWwjWjTRuXXn6tMQKjNvVJm-BlE4G4R3yoi6zXmEDPO8D2KY0DG-hoWB872V4qcoJXGYa9C4hl-qKMBzb1pqjrjPlaCFtJkjo34OxS7euNgmVfxcMeO1r5HWgvxL4PQwlxYZXhYrRS9cnuHniCWMXgx6s1G7d4aJm1qzF5ZNZuGCVwDA3lnOV_rMGpAYjdwJtZ1LjzRX7Jz6NefOzCALNpjWojFSiUdlsh7chJRvVV3jsDYMxOpPhEdWAaGmMdgK0v-tK88bleMxaOjepZrkaTGMfQ9Ptdwg0mPpAGoty7wxC8bHbC3eZ0C-ngEWTRa_S9KoRaF1BBwDjHsz9kr4fTNewiRVtLCmb9TYkhRO6JMvh1gskccd_WSMA&type=pzzlSlider&result=0

**Comment by happy0717** [comment]
哎 data参数是google的验证码  不传不行  google验证码太反人类了

**Comment by Liuxianlu** [comment]
70340008
***@***.***



&nbsp;
这个方法过时了，另找方法吧，官方更新了，加了几个加密的参数。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Liuxianlu/pikpak_werbio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月9日(星期一) 晚上6:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Liuxianlu/pikpak_werbio] 老板  https://user.mypikpak.com/credit/v1/report 接口 400 (Issue #4)





 
哎 data参数是google的验证码  不传不行  google验证码太反人类了
